name: Run C++ Program Manually

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Inspect hardware specs
      run: |
            echo "=== CPU INFO ==="
            lscpu | grep -E "Model name|Core\(s\) per socket|Thread\(s\) per core|Architecture"
            echo "=== MEMORY INFO ==="
            free -h

    
    - name: Initialize Eco-CI
      uses: green-coding-solutions/eco-ci-energy-estimation@v1
      with:
        task: initialize
   

    - name: Compile C++ program
      run: g++ -O3 -march=native -std=c++11 src/test_lis.cpp -o scripts/test_lis


    - name: Start Energy Measurement
      uses: green-coding-solutions/eco-ci-energy-estimation@v1
      with:
        task: start-measurement

    
    - name: Execute program
      run: scripts/test_lis

    
    - name: Get Energy Measurement
      uses: green-coding-solutions/eco-ci-energy-estimation@v1
      with:
        task: get-measurement
        label: 'C++ Compile and Execution'

    
    - name: Display Final Energy Results
      uses: green-coding-solutions/eco-ci-energy-estimation@v1
      with:
        task: display-results

    
    - name: Upload output file
      uses: actions/upload-artifact@v4
      with:
        name: program-output-file
        path: "*.txt"
