name: Run C++ Program Manually

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Επιτρέπει τη χειροκίνητη εκτέλεσ

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Inspect hardware specs
      run: |
            echo "=== CPU INFO ==="
            lscpu | grep -E "Model name|Core\(s\) per socket|Thread\(s\) per core|Architecture"
            echo "=== MEMORY INFO ==="
            free -h

    - name: Compile C++ program
      run: g++ -O3 -march=native -std=c++11 src/test_lis.cpp -o scripts/test_lis

    # Εμφάνιση του stdout στα logs αυτού του βήματος
    - name: Execute program
      run: scripts/test_lis

    # Εντοπισμός και ανέβασμα του αρχείου κειμένου που δημιουργήθηκε
    - name: Upload output file
      uses: actions/upload-artifact@v4
      with:
        name: program-output-file
        path: "*.txt"            
