name: Run line pattern (offset=100000) and measure energy

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Inspect hardware specs
      run: |
            echo "=== CPU INFO ==="
            lscpu | grep -E "Model name|Core\(s\) per socket|Thread\(s\) per core|Architecture"
            echo "=== MEMORY INFO ==="
            free -h

    - name: Compile C++ program
      run: g++ -O3 -march=native -std=c++11 src/test_lis.cpp -o scripts/test_lis

    
    - name: Start Energy Measurement
      uses: green-coding-solutions/eco-ci-energy-estimation@v5
      with:
        task: start-measurement

    
    - name: Execute program with 1T
      run: scripts/test_lis -size 100000000 -trials 5 -pattern line -offset 100000 -algo 1T

    - name: Get Energy Measurement for 1T
      uses: green-coding-solutions/eco-ci-energy-estimation@v5
      with:
        task: get-measurement
        label: 'C++ Execution 1T'

    
    - name: Execute program with 2T
      run: scripts/test_lis -size 100000000 -trials 5 -pattern line -offset 100000 -algo 2T

    - name: Get Energy Measurement for 2T
      uses: green-coding-solutions/eco-ci-energy-estimation@v5
      with:
        task: get-measurement
        label: 'C++ Execution 2T'

    
    - name: Display Final Energy Results
      uses: green-coding-solutions/eco-ci-energy-estimation@v5
      with:
        task: display-results
        send-data: false
        display-table: true


    - name: Upload output files
      uses: actions/upload-artifact@v4
      with:
        name: program-output-and-energy
        path: |
          *.txt         